"""initial schema

Revision ID: 89c5e1acdef7
Revises: 
Create Date: 2026-03-19 21:52:09.501743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89c5e1acdef7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=True),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('entity_type', sa.Text(), nullable=False),
    sa.Column('entity_id', sa.Text(), nullable=True),
    sa.Column('before_state', sa.Text(), nullable=True),
    sa.Column('after_state', sa.Text(), nullable=True),
    sa.Column('tool_name', sa.Text(), nullable=True),
    sa.Column('request_id', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_log_entity', 'audit_log', ['entity_type', 'entity_id'], unique=False)
    op.create_index('idx_audit_log_request', 'audit_log', ['request_id'], unique=False)
    op.create_index('idx_audit_log_timestamp', 'audit_log', ['timestamp'], unique=False)
    op.create_table('meal_plans',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('start_date', sa.Text(), nullable=False),
    sa.Column('end_date', sa.Text(), nullable=False),
    sa.Column('preferences', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nutrition_cache',
    sa.Column('food_name', sa.Text(), nullable=False),
    sa.Column('fdc_id', sa.Text(), nullable=True),
    sa.Column('calories', sa.Float(), nullable=True),
    sa.Column('protein_g', sa.Float(), nullable=True),
    sa.Column('fat_g', sa.Float(), nullable=True),
    sa.Column('carbs_g', sa.Float(), nullable=True),
    sa.Column('fiber_g', sa.Float(), nullable=True),
    sa.Column('sugar_g', sa.Float(), nullable=True),
    sa.Column('sodium_mg', sa.Float(), nullable=True),
    sa.Column('full_nutrients', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('fetched_at', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('food_name')
    )
    op.create_table('recipes',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('area', sa.Text(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('source_api', sa.Text(), nullable=True),
    sa.Column('source_id', sa.Text(), nullable=True),
    sa.Column('prep_time_min', sa.Integer(), nullable=True),
    sa.Column('cook_time_min', sa.Integer(), nullable=True),
    sa.Column('servings', sa.Integer(), nullable=False),
    sa.Column('difficulty', sa.Text(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_recipes_area', 'recipes', ['area'], unique=False)
    op.create_index('idx_recipes_category', 'recipes', ['category'], unique=False)
    op.create_index('idx_recipes_deleted', 'recipes', ['is_deleted'], unique=False)
    op.create_index('idx_recipes_source', 'recipes', ['source_api', 'source_id'], unique=False)
    op.create_table('user_profiles',
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('dietary_restrictions', sa.Text(), nullable=True),
    sa.Column('allergies', sa.Text(), nullable=True),
    sa.Column('preferred_cuisines', sa.Text(), nullable=True),
    sa.Column('default_servings', sa.Integer(), nullable=False),
    sa.Column('unit_system', sa.Text(), server_default=sa.text("'metric'"), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('favorites',
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('recipe_id', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('saved_at', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'recipe_id')
    )
    op.create_index('idx_favorites_user', 'favorites', ['user_id'], unique=False)
    op.create_table('meal_plan_items',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('plan_id', sa.Text(), nullable=False),
    sa.Column('day_date', sa.Text(), nullable=False),
    sa.Column('meal_type', sa.Text(), nullable=False),
    sa.Column('recipe_id', sa.Text(), nullable=True),
    sa.Column('custom_meal', sa.Text(), nullable=True),
    sa.Column('servings', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['meal_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_meal_plan_items_date', 'meal_plan_items', ['day_date'], unique=False)
    op.create_index('idx_meal_plan_items_plan', 'meal_plan_items', ['plan_id'], unique=False)
    op.create_table('recipe_ingredients',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('recipe_id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('unit', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_recipe_ingredients_recipe', 'recipe_ingredients', ['recipe_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_recipe_ingredients_recipe', table_name='recipe_ingredients')
    op.drop_table('recipe_ingredients')
    op.drop_index('idx_meal_plan_items_plan', table_name='meal_plan_items')
    op.drop_index('idx_meal_plan_items_date', table_name='meal_plan_items')
    op.drop_table('meal_plan_items')
    op.drop_index('idx_favorites_user', table_name='favorites')
    op.drop_table('favorites')
    op.drop_table('user_profiles')
    op.drop_index('idx_recipes_source', table_name='recipes')
    op.drop_index('idx_recipes_deleted', table_name='recipes')
    op.drop_index('idx_recipes_category', table_name='recipes')
    op.drop_index('idx_recipes_area', table_name='recipes')
    op.drop_table('recipes')
    op.drop_table('nutrition_cache')
    op.drop_table('meal_plans')
    op.drop_index('idx_audit_log_timestamp', table_name='audit_log')
    op.drop_index('idx_audit_log_request', table_name='audit_log')
    op.drop_index('idx_audit_log_entity', table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
